// <auto-generated />
using System;
using HotelBooking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HotelBooking.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    partial class HotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HotelBooking.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Habitación para una persona, cómoda y acogedora",
                            Nombre = "Individual"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Habitación para dos personas con cama doble o twin",
                            Nombre = "Doble"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Suite de lujo con sala de estar y vista panorámica",
                            Nombre = "Suite"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Habitación amplia para familias, ideal para 4 personas",
                            Nombre = "Familiar"
                        });
                });

            modelBuilder.Entity("HotelBooking.Models.Habitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Servicios")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Habitaciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 1,
                            CategoriaId = 1,
                            Descripcion = "Acogedora habitación individual con todas las comodidades. Perfecta para viajeros de negocios.",
                            Disponible = true,
                            Nombre = "Habitación Individual Estándar",
                            PrecioPorNoche = 250m,
                            Servicios = "WiFi Gratis, TV 40\", Aire Acondicionado, Baño Privado, Frigobar"
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 2,
                            CategoriaId = 2,
                            Descripcion = "Espaciosa habitación doble con vista a la ciudad. Ideal para parejas o compañeros de viaje.",
                            Disponible = true,
                            Nombre = "Habitación Doble Superior",
                            PrecioPorNoche = 380m,
                            Servicios = "WiFi Gratis, TV 50\", Aire Acondicionado, Baño Privado, Frigobar, Balcón"
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 2,
                            CategoriaId = 3,
                            Descripcion = "Lujosa suite con sala de estar separada y vista panorámica al valle de Cochabamba.",
                            Disponible = true,
                            Nombre = "Suite Ejecutiva",
                            PrecioPorNoche = 750m,
                            Servicios = "WiFi Gratis, Smart TV 65\", Jacuzzi, Sala de Estar, Cocina Equipada, Vista Panorámica"
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 4,
                            CategoriaId = 4,
                            Descripcion = "Amplia suite familiar con dos habitaciones, perfecta para familias con niños.",
                            Disponible = true,
                            Nombre = "Suite Familiar Deluxe",
                            PrecioPorNoche = 950m,
                            Servicios = "WiFi Gratis, 2 TVs, Aire Acondicionado, 2 Baños, Sala Familiar, Desayuno Incluido"
                        });
                });

            modelBuilder.Entity("HotelBooking.Models.ImagenHabitacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.ToTable("ImagenesHabitacion");
                });

            modelBuilder.Entity("HotelBooking.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaEntrada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPagar")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HabitacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("HotelBooking.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HotelBooking.Models.Habitacion", b =>
                {
                    b.HasOne("HotelBooking.Models.Categoria", "Categoria")
                        .WithMany("Habitaciones")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("HotelBooking.Models.ImagenHabitacion", b =>
                {
                    b.HasOne("HotelBooking.Models.Habitacion", "Habitacion")
                        .WithMany("Imagenes")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("HotelBooking.Models.Reserva", b =>
                {
                    b.HasOne("HotelBooking.Models.Habitacion", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HotelBooking.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Habitacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HotelBooking.Models.Categoria", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("HotelBooking.Models.Habitacion", b =>
                {
                    b.Navigation("Imagenes");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HotelBooking.Models.Usuario", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
